name: "open_process_mining"
version: "1.0.0"
config-version: 2

profile: "open_process_mining"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  open_process_mining:
    staging:
      +materialized: view
    marts:
      +materialized: table

seeds:
  open_process_mining:
    raw_order_to_cash_2024:
      +schema: public
      +column_types:
        order_id: varchar
        order_status: varchar
        status_changed_at: timestamp
        employee_id: varchar

    raw_employee_onboarding:
      +schema: public
      +column_types:
        application_id: varchar
        application_date: timestamp
        candidate_name: varchar
        position: varchar
        status: varchar
        employee_id: varchar

    master_employees:
      +schema: public
      +column_types:
        employee_id: varchar
        employee_name: varchar
        role: varchar
        department_id: varchar

    master_departments:
      +schema: public
      +column_types:
        department_id: varchar
        department_name: varchar
        department_type: varchar
        parent_department_id: varchar

    outcome_order_to_cash_2024:
      +schema: public
      +column_types:
        process_type: varchar
        case_id: varchar
        metric_name: varchar
        metric_value: numeric
        metric_unit: varchar

    outcome_employee_onboarding:
      +schema: public
      +column_types:
        process_type: varchar
        case_id: varchar
        metric_name: varchar
        metric_value: numeric
        metric_unit: varchar
