version: 2

models:
  - name: fct_event_log
    description: "Event log fact table in standard process mining format"
    columns:
      - name: process_type
        description: "Process type identifier (e.g., 'order-delivery', 'employee-onboarding')"
        tests:
          - not_null
          - accepted_values:
              values: ["order-delivery", "employee-onboarding"]
      - name: case_id
        description: "Case identifier (process instance)"
        tests:
          - not_null
      - name: activity
        description: "Activity name"
        tests:
          - not_null
      - name: timestamp
        description: "Event timestamp"
        tests:
          - not_null
      - name: resource
        description: "Resource that performed the activity"
        tests:
          - not_null
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - process_type
            - case_id
            - timestamp
            - activity
