version: 2

models:
  - name: stg_all_events
    description: "Unified staging table combining all process types"
    columns:
      - name: process_type
        description: "Process type identifier"
        tests:
          - not_null
          - accepted_values:
              values:
                [
                  "order-to-cash",
                  "employee-onboarding",
                  "itsm",
                  "billing",
                  "invoice-approval",
                  "system-development",
                ]
      - name: case_id
        description: "Case identifier"
        tests:
          - not_null
      - name: activity
        description: "Activity name"
        tests:
          - not_null
      - name: timestamp
        description: "Event timestamp"
        tests:
          - not_null
      - name: resource
        description: "Resource (employee_id)"
        tests:
          - not_null
